export const metadata = {
  title: "Privacy Policy · Horizon",
  description: "How Horizon collects, uses, and protects your information.",
};

const LAST_UPDATED = "May 15, 2026";

export default function PrivacyPage() {
  return (
    <div className="max-w-2xl">
      <div className="mb-10">
        <h2 className="text-xs font-semibold uppercase tracking-widest text-emerald-500 mb-3">Privacy Policy</h2>
        <p className="text-2xl font-bold text-gray-900 dark:text-white leading-snug mb-2">
          Your privacy, plainly explained.
        </p>
        <p className="text-xs text-gray-400 dark:text-gray-500">Last updated {LAST_UPDATED}</p>
      </div>

      <div className="space-y-6">

        <Section title="Overview">
          Horizon is an educational financial dashboard. We collect the minimum information necessary to operate the service and do not sell, rent, or share your personal data with third parties for marketing purposes.
        </Section>

        <Section title="Information We Collect">
          <SubHeading>Account information</SubHeading>
          When you create an account, we store your chosen username and a bcrypt hash of your password. We never store your password in plain text. We do not collect your name, email address, or payment information.

          <SubHeading>Session data</SubHeading>
          When you sign in, we set a secure, HttpOnly cookie (<code className="text-xs bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">horizon_session</code>) containing a signed JWT. This cookie expires after 7 days and is used solely to keep you authenticated. It is not used for tracking or advertising.

          <SubHeading>Guest access</SubHeading>
          If you enter as a guest, a temporary session is created with no account data stored beyond the session cookie.
        </Section>

        <Section title="How We Use Your Information">
          We use your account information exclusively to:
          <ul className="mt-2 space-y-1 list-disc list-inside text-xs text-gray-500 dark:text-gray-400">
            <li>Authenticate you when you sign in</li>
            <li>Maintain your session across page visits</li>
          </ul>
          <p className="mt-2">We do not use your data for advertising, profiling, or analytics.</p>
        </Section>

        <Section title="Data Storage">
          Account data (username and hashed password) is stored in AWS DynamoDB in the us-east-1 region. Data is encrypted at rest and in transit. We retain your account data for as long as your account exists. You may request deletion at any time by contacting us.
        </Section>

        <Section title="Third-Party Data Sources">
          Horizon displays data from the following external services. These services are used to power the dashboard — they do not receive any of your personal account information.
          <ul className="mt-2 space-y-1 list-disc list-inside text-xs text-gray-500 dark:text-gray-400">
            <li><span className="font-medium text-gray-700 dark:text-gray-300">FRED (Federal Reserve Bank of St. Louis)</span> — macroeconomic indicators</li>
            <li><span className="font-medium text-gray-700 dark:text-gray-300">Polygon.io</span> — US equity market data</li>
            <li><span className="font-medium text-gray-700 dark:text-gray-300">Anthropic (Claude)</span> — AI-generated market and economic summaries</li>
          </ul>
        </Section>

        <Section title="AI-Generated Content">
          Some pages on Horizon include summaries generated by Claude, Anthropic&apos;s AI model. These summaries are based solely on publicly available market and economic data — no personal information is sent to Anthropic. AI-generated content is clearly labelled and is not financial advice.
        </Section>

        <Section title="Cookies">
          We use one cookie: <code className="text-xs bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">horizon_session</code> for authentication, and <code className="text-xs bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">theme</code> stored in localStorage to remember your light/dark mode preference. We do not use advertising cookies, tracking pixels, or third-party analytics.
        </Section>

        <Section title="Your Rights">
          You may request access to, correction of, or deletion of your account data at any time by emailing us. We will respond within 30 days.
        </Section>

        <Section title="Children">
          Horizon is not directed at children under 13. We do not knowingly collect data from children under 13.
        </Section>

        <Section title="Changes to This Policy">
          If we make material changes to this policy, we will update the &quot;Last updated&quot; date above. Continued use of Horizon after changes constitutes acceptance of the updated policy.
        </Section>

        <div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900/30 p-4">
          <h3 className="text-xs font-semibold uppercase tracking-widest text-emerald-500 mb-2">Contact</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
            Questions or requests regarding your data? Reach out to{" "}
            <a href="mailto:shantanu.r.bal@gmail.com" className="text-emerald-500 hover:text-emerald-400 transition-colors">
              shantanu.r.bal@gmail.com
            </a>
          </p>
        </div>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900/30 p-5">
      <h3 className="text-xs font-semibold uppercase tracking-widest text-emerald-500 mb-3">{title}</h3>
      <div className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed space-y-2">
        {children}
      </div>
    </div>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <p className="font-medium text-gray-700 dark:text-gray-300 mt-3 mb-0.5">{children}</p>;
}
