export const NASDAQ100_TICKERS = [
  "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "TSLA", "AVGO", "COST",
  "NFLX", "AMD", "ADBE", "PEP", "CSCO", "INTU", "CMCSA", "TXN", "AMGN",
  "QCOM", "HON", "AMAT", "ISRG", "BKNG", "VRTX", "ADP", "GILD", "MDLZ", "ADI",
  "PANW", "REGN", "MU", "LRCX", "SNPS", "KLAC", "CRWD", "MELI", "CDNS", "ORLY",
  "MAR", "MNST", "KHC", "CEG", "FTNT", "PAYX", "WDAY", "PYPL", "CSGP", "ABNB",
  "MRNA", "CPRT", "NXPI", "FAST", "DXCM", "IDXX", "GEHC", "ODFL", "KDP", "ROST",
  "TTWO", "ON", "ZS", "VRSK", "EXC", "FANG", "BKR", "AEP", "XEL", "CTSH",
  "BIIB", "DLTR", "LULU", "EA", "PCAR", "ROP", "CHTR", "CTAS", "MCHP", "TEAM", "DDOG", "MDB", "ILMN", "EBAY", "TTD", "SIRI", "RIVN", "CDW", "SBUX", "DASH", "GEHC", "GFS", "SMCI", "FSLR", "ENPH", "MRVL",
];

export const NASDAQ100_NAMES: Record<string, string> = {
  AAPL: "Apple", MSFT: "Microsoft", NVDA: "NVIDIA", AMZN: "Amazon", META: "Meta Platforms",
  GOOGL: "Alphabet A", TSLA: "Tesla", AVGO: "Broadcom", COST: "Costco",
  NFLX: "Netflix", AMD: "Advanced Micro Devices", ADBE: "Adobe", PEP: "PepsiCo", CSCO: "Cisco", INTU: "Intuit", CMCSA: "Comcast", TXN: "Texas Instruments",
  AMGN: "Amgen", QCOM: "Qualcomm", HON: "Honeywell", AMAT: "Applied Materials",
  ISRG: "Intuitive Surgical", BKNG: "Booking Holdings", VRTX: "Vertex Pharmaceuticals",
  ADP: "Automatic Data Processing", GILD: "Gilead Sciences", MDLZ: "Mondelez",
  ADI: "Analog Devices", PANW: "Palo Alto Networks", REGN: "Regeneron", MU: "Micron Technology",
  LRCX: "Lam Research", SNPS: "Synopsys", KLAC: "KLA Corp", CRWD: "CrowdStrike",
  MELI: "MercadoLibre", CDNS: "Cadence Design", ORLY: "O'Reilly Automotive", MAR: "Marriott",
  MNST: "Monster Beverage", KHC: "Kraft Heinz", CEG: "Constellation Energy", FTNT: "Fortinet",
  PAYX: "Paychex", WDAY: "Workday", PYPL: "PayPal", CSGP: "CoStar Group", ABNB: "Airbnb",
  MRNA: "Moderna", CPRT: "Copart", NXPI: "NXP Semiconductors", FAST: "Fastenal",
  DXCM: "DexCom", IDXX: "IDEXX Laboratories", GEHC: "GE HealthCare", ODFL: "Old Dominion Freight",
  KDP: "Keurig Dr Pepper", ROST: "Ross Stores", TTWO: "Take-Two Interactive",
  ON: "ON Semiconductor", ZS: "Zscaler", VRSK: "Verisk Analytics", EXC: "Exelon",
  FANG: "Diamondback Energy", BKR: "Baker Hughes", AEP: "American Electric Power",
  XEL: "Xcel Energy", CTSH: "Cognizant", BIIB: "Biogen", DLTR: "Dollar Tree",
  LULU: "Lululemon", EA: "Electronic Arts", PCAR: "PACCAR", ROP: "Roper Technologies",
  CHTR: "Charter Communications", CTAS: "Cintas", MCHP: "Microchip Technology", TEAM: "Atlassian", DDOG: "Datadog", MDB: "MongoDB", ILMN: "Illumina",
  EBAY: "eBay", TTD: "The Trade Desk", SIRI: "Sirius XM",
  RIVN: "Rivian", CDW: "CDW Corp", SBUX: "Starbucks",
  DASH: "DoorDash", GFS: "GlobalFoundries", SMCI: "Super Micro Computer",
  FSLR: "First Solar", ENPH: "Enphase Energy", MRVL: "Marvell Technology",
};

export const NASDAQ100_SECTORS: Record<string, string> = {
  AAPL: "Tech Hardware", MSFT: "Software", NVDA: "Semiconductors", AMZN: "Retail",
  META: "Media", GOOGL: "Media", TSLA: "Consumer Goods", AVGO: "Semiconductors",
  COST: "Food & Beverage", NFLX: "Media", AMD: "Semiconductors", ADBE: "Software",
  PEP: "Food & Beverage", CSCO: "Tech Hardware", INTU: "Software",
  CMCSA: "Telecom", TXN: "Semiconductors", AMGN: "Pharma & Biotech", QCOM: "Semiconductors",
  HON: "Capital Goods", AMAT: "Semiconductors", ISRG: "Health Services", BKNG: "Consumer Services",
  VRTX: "Pharma & Biotech", ADP: "Software", GILD: "Pharma & Biotech", MDLZ: "Food & Beverage",
  ADI: "Semiconductors", PANW: "Software", REGN: "Pharma & Biotech", MU: "Semiconductors",
  LRCX: "Semiconductors", SNPS: "Software", KLAC: "Semiconductors", CRWD: "Software",
  MELI: "Retail", CDNS: "Software", ORLY: "Retail", MAR: "Consumer Services",
  MNST: "Food & Beverage", KHC: "Food & Beverage", CEG: "Utilities", FTNT: "Software",
  PAYX: "Software", WDAY: "Software", PYPL: "Financial Services", CSGP: "REITs",
  ABNB: "Consumer Services", MRNA: "Pharma & Biotech", CPRT: "Transportation",
  NXPI: "Semiconductors", FAST: "Capital Goods", DXCM: "Health Services", IDXX: "Health Services",
  GEHC: "Health Services", ODFL: "Transportation", KDP: "Food & Beverage", ROST: "Retail",
  TTWO: "Media", ON: "Semiconductors", ZS: "Software", VRSK: "Prof. Services",
  EXC: "Utilities", FANG: "Energy", BKR: "Energy", AEP: "Utilities", XEL: "Utilities",
  CTSH: "Software", BIIB: "Pharma & Biotech", DLTR: "Retail", LULU: "Consumer Goods",
  EA: "Media", PCAR: "Capital Goods", ROP: "Capital Goods", CHTR: "Telecom",
  CTAS: "Prof. Services", MCHP: "Semiconductors", TEAM: "Software",
  DDOG: "Software", MDB: "Software", ILMN: "Pharma & Biotech", EBAY: "Retail", TTD: "Software", SIRI: "Media", RIVN: "Consumer Goods", CDW: "Tech Hardware", SBUX: "Consumer Services", DASH: "Consumer Services",
  GFS: "Semiconductors", SMCI: "Tech Hardware", FSLR: "Semiconductors",
  ENPH: "Semiconductors", MRVL: "Semiconductors",
};
