export const NASDAQ100_TICKERS = [
  "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "TSLA", "AVGO", "COST",
  "NFLX", "AMD", "ADBE", "PEP", "CSCO", "INTU", "CMCSA", "TXN", "AMGN",
  "QCOM", "HON", "AMAT", "ISRG", "BKNG", "VRTX", "ADP", "GILD", "MDLZ", "ADI",
  "PANW", "REGN", "MU", "LRCX", "SNPS", "KLAC", "CRWD", "MELI", "CDNS", "ORLY",
  "MAR", "MNST", "KHC", "CEG", "FTNT", "PAYX", "WDAY", "PYPL", "ABNB",
  "CPRT", "NXPI", "FAST", "DXCM", "IDXX", "GEHC", "ODFL", "KDP", "ROST",
  "TTWO", "ZS", "VRSK", "EXC", "FANG", "BKR", "AEP", "XEL", "CTSH",
  "EA", "PCAR", "ROP", "CHTR", "CTAS", "MCHP", "DDOG", "MRVL", "SBUX", "DASH",
  "APP", "ARM", "ASML", "ADSK", "ALNY", "AXON", "CCEP", "CSX", "FER",
  "INSM", "INTC", "LIN", "LITE", "MPWR", "MSTR", "PDD", "PLTR",
  "SHOP", "SNDK", "STX", "TMUS", "TRI", "WBD", "WDC", "WMT",
];

export const NASDAQ100_NAMES: Record<string, string> = {
  AAPL: "Apple", MSFT: "Microsoft", NVDA: "NVIDIA", AMZN: "Amazon", META: "Meta Platforms",
  GOOGL: "Alphabet", TSLA: "Tesla", AVGO: "Broadcom", COST: "Costco",
  NFLX: "Netflix", AMD: "Advanced Micro Devices", ADBE: "Adobe", PEP: "PepsiCo", CSCO: "Cisco",
  INTU: "Intuit", CMCSA: "Comcast", TXN: "Texas Instruments", AMGN: "Amgen", QCOM: "Qualcomm",
  HON: "Honeywell", AMAT: "Applied Materials", ISRG: "Intuitive Surgical", BKNG: "Booking Holdings",
  VRTX: "Vertex Pharmaceuticals", ADP: "Automatic Data Processing", GILD: "Gilead Sciences",
  MDLZ: "Mondelez", ADI: "Analog Devices", PANW: "Palo Alto Networks", REGN: "Regeneron",
  MU: "Micron Technology", LRCX: "Lam Research", SNPS: "Synopsys", KLAC: "KLA Corp",
  CRWD: "CrowdStrike", MELI: "MercadoLibre", CDNS: "Cadence Design", ORLY: "O'Reilly Automotive",
  MAR: "Marriott", MNST: "Monster Beverage", KHC: "Kraft Heinz", CEG: "Constellation Energy",
  FTNT: "Fortinet", PAYX: "Paychex", WDAY: "Workday", PYPL: "PayPal", ABNB: "Airbnb",
  CPRT: "Copart", NXPI: "NXP Semiconductors", FAST: "Fastenal", DXCM: "DexCom",
  IDXX: "IDEXX Laboratories", GEHC: "GE HealthCare", ODFL: "Old Dominion Freight",
  KDP: "Keurig Dr Pepper", ROST: "Ross Stores", TTWO: "Take-Two Interactive",
  ZS: "Zscaler", VRSK: "Verisk Analytics", EXC: "Exelon", FANG: "Diamondback Energy",
  BKR: "Baker Hughes", AEP: "American Electric Power", XEL: "Xcel Energy", CTSH: "Cognizant",
  EA: "Electronic Arts", PCAR: "PACCAR", ROP: "Roper Technologies", CHTR: "Charter Communications",
  CTAS: "Cintas", MCHP: "Microchip Technology", DDOG: "Datadog", MRVL: "Marvell Technology",
  SBUX: "Starbucks", DASH: "DoorDash",
  APP: "AppLovin", ARM: "Arm Holdings", ASML: "ASML Holding", ADSK: "Autodesk",
  ALNY: "Alnylam Pharmaceuticals", AXON: "Axon Enterprise", CCEP: "Coca-Cola Europacific Partners",
  CSX: "CSX Corporation", FER: "Ferrovial", INSM: "Insmed", INTC: "Intel",
  LIN: "Linde", LITE: "Lumentum Holdings", MPWR: "Monolithic Power Systems",
  MSTR: "Strategy Inc", PDD: "PDD Holdings", PLTR: "Palantir Technologies",
  SHOP: "Shopify", SNDK: "Sandisk", STX: "Seagate Technology", TMUS: "T-Mobile US",
  TRI: "Thomson Reuters", WBD: "Warner Bros. Discovery", WDC: "Western Digital", WMT: "Walmart",
};

export const NASDAQ100_SECTORS: Record<string, string> = {
  AAPL: "Tech Hardware", MSFT: "Software", NVDA: "Semiconductors", AMZN: "Retail",
  META: "Media", GOOGL: "Media", TSLA: "Consumer Goods", AVGO: "Semiconductors",
  COST: "Food & Beverage", NFLX: "Media", AMD: "Semiconductors", ADBE: "Software",
  PEP: "Food & Beverage", CSCO: "Tech Hardware", INTU: "Software",
  CMCSA: "Telecom", TXN: "Semiconductors", AMGN: "Pharma & Biotech", QCOM: "Semiconductors",
  HON: "Capital Goods", AMAT: "Semiconductors", ISRG: "Health Services", BKNG: "Consumer Services",
  VRTX: "Pharma & Biotech", ADP: "Software", GILD: "Pharma & Biotech", MDLZ: "Food & Beverage",
  ADI: "Semiconductors", PANW: "Software", REGN: "Pharma & Biotech", MU: "Semiconductors",
  LRCX: "Semiconductors", SNPS: "Software", KLAC: "Semiconductors", CRWD: "Software",
  MELI: "Retail", CDNS: "Software", ORLY: "Retail", MAR: "Consumer Services",
  MNST: "Food & Beverage", KHC: "Food & Beverage", CEG: "Utilities", FTNT: "Software",
  PAYX: "Software", WDAY: "Software", PYPL: "Financial Services",
  ABNB: "Consumer Services", CPRT: "Transportation",
  NXPI: "Semiconductors", FAST: "Capital Goods", DXCM: "Health Services", IDXX: "Health Services",
  GEHC: "Health Services", ODFL: "Transportation", KDP: "Food & Beverage", ROST: "Retail",
  TTWO: "Media", ZS: "Software", VRSK: "Prof. Services",
  EXC: "Utilities", FANG: "Energy", BKR: "Energy", AEP: "Utilities", XEL: "Utilities",
  CTSH: "Software", EA: "Media", PCAR: "Capital Goods", ROP: "Capital Goods",
  CHTR: "Telecom", CTAS: "Prof. Services", MCHP: "Semiconductors",
  DDOG: "Software", MRVL: "Semiconductors", SBUX: "Consumer Services", DASH: "Consumer Services",
  APP: "Software", ARM: "Semiconductors", ASML: "Semiconductors", ADSK: "Software",
  ALNY: "Pharma & Biotech", AXON: "Capital Goods", CCEP: "Food & Beverage",
  CSX: "Transportation", FER: "Capital Goods", INSM: "Pharma & Biotech", INTC: "Semiconductors",
  LIN: "Materials", LITE: "Tech Hardware", MPWR: "Semiconductors",
  MSTR: "Financial Services", PDD: "Retail", PLTR: "Software",
  SHOP: "Software", SNDK: "Tech Hardware", STX: "Tech Hardware", TMUS: "Telecom",
  TRI: "Media", WBD: "Media", WDC: "Tech Hardware", WMT: "Retail",
};
