export const NASDAQ100_TICKERS = [
  "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "TSLA", "AVGO", "COST",
  "NFLX", "AMD", "ADBE", "ASML", "PEP", "CSCO", "INTU", "CMCSA", "TXN", "AMGN",
  "QCOM", "HON", "AMAT", "ISRG", "BKNG", "VRTX", "ADP", "GILD", "MDLZ", "ADI",
  "PANW", "REGN", "MU", "LRCX", "SNPS", "KLAC", "CRWD", "MELI", "CDNS", "ORLY",
  "MAR", "MNST", "KHC", "CEG", "FTNT", "PAYX", "WDAY", "PYPL", "CSGP", "ABNB",
  "MRNA", "CPRT", "NXPI", "FAST", "DXCM", "IDXX", "GEHC", "ODFL", "KDP", "ROST",
  "TTWO", "ON", "ZS", "VRSK", "EXC", "FANG", "BKR", "AEP", "XEL", "CTSH",
  "BIIB", "DLTR", "LULU", "EA", "PCAR", "ROP", "CHTR", "CTAS", "MCHP", "ANSS",
  "TEAM", "DDOG", "MDB", "ILMN", "WBA", "EBAY", "TTD", "SIRI", "RIVN", "ARM",
  "CDW", "SBUX", "DASH", "GEHC", "GFS", "SMCI", "FSLR", "ENPH", "MRVL",
];

export const NASDAQ100_NAMES: Record<string, string> = {
  AAPL: "Apple", MSFT: "Microsoft", NVDA: "NVIDIA", AMZN: "Amazon", META: "Meta Platforms",
  GOOGL: "Alphabet A", GOOG: "Alphabet C", TSLA: "Tesla", AVGO: "Broadcom", COST: "Costco",
  NFLX: "Netflix", AMD: "Advanced Micro Devices", ADBE: "Adobe", ASML: "ASML Holding",
  PEP: "PepsiCo", CSCO: "Cisco", INTU: "Intuit", CMCSA: "Comcast", TXN: "Texas Instruments",
  AMGN: "Amgen", QCOM: "Qualcomm", HON: "Honeywell", AMAT: "Applied Materials",
  ISRG: "Intuitive Surgical", BKNG: "Booking Holdings", VRTX: "Vertex Pharmaceuticals",
  ADP: "Automatic Data Processing", GILD: "Gilead Sciences", MDLZ: "Mondelez",
  ADI: "Analog Devices", PANW: "Palo Alto Networks", REGN: "Regeneron", MU: "Micron Technology",
  LRCX: "Lam Research", SNPS: "Synopsys", KLAC: "KLA Corp", CRWD: "CrowdStrike",
  MELI: "MercadoLibre", CDNS: "Cadence Design", ORLY: "O'Reilly Automotive", MAR: "Marriott",
  MNST: "Monster Beverage", KHC: "Kraft Heinz", CEG: "Constellation Energy", FTNT: "Fortinet",
  PAYX: "Paychex", WDAY: "Workday", PYPL: "PayPal", CSGP: "CoStar Group", ABNB: "Airbnb",
  MRNA: "Moderna", CPRT: "Copart", NXPI: "NXP Semiconductors", FAST: "Fastenal",
  DXCM: "DexCom", IDXX: "IDEXX Laboratories", GEHC: "GE HealthCare", ODFL: "Old Dominion Freight",
  KDP: "Keurig Dr Pepper", ROST: "Ross Stores", TTWO: "Take-Two Interactive",
  ON: "ON Semiconductor", ZS: "Zscaler", VRSK: "Verisk Analytics", EXC: "Exelon",
  FANG: "Diamondback Energy", BKR: "Baker Hughes", AEP: "American Electric Power",
  XEL: "Xcel Energy", CTSH: "Cognizant", BIIB: "Biogen", DLTR: "Dollar Tree",
  LULU: "Lululemon", EA: "Electronic Arts", PCAR: "PACCAR", ROP: "Roper Technologies",
  CHTR: "Charter Communications", CTAS: "Cintas", MCHP: "Microchip Technology", ANSS: "ANSYS",
  TEAM: "Atlassian", DDOG: "Datadog", MDB: "MongoDB", ILMN: "Illumina",
  WBA: "Walgreens Boots Alliance", EBAY: "eBay", TTD: "The Trade Desk", SIRI: "Sirius XM",
  RIVN: "Rivian", ARM: "Arm Holdings", CDW: "CDW Corp", SBUX: "Starbucks",
  DASH: "DoorDash", GFS: "GlobalFoundries", SMCI: "Super Micro Computer",
  FSLR: "First Solar", ENPH: "Enphase Energy", MRVL: "Marvell Technology",
};
