export const RUSSELL2000_TICKERS = [
  // Technology
  "APPN", "BAND", "BIGC", "BLKB", "COUR", "DOMO", "EVTC", "EXTR",
  "GDYN", "HLIT", "JAMF", "LSCC", "MARA", "MGNI", "NTGR", "PLTK",
  "RELY", "RXRX", "SEAT", "STEP", "TRIP", "UPST", "YEXT", "ZETA",
  "AMSWA", "CWAN", "KFRC", "NRDS", "RIOT", "WULF", "CIFR", "IREN",
  "CLOV", "HOOD", "LAZR", "LCID", "JOBY", "ACHR", "LILM", "ARVL",
  // Healthcare & Biotech
  "ACAD", "ARDX", "ATEC", "AXSM", "BCRX", "BCYC", "CNMD", "HRMY",
  "HIMS", "IRMD", "KMDA", "PTCT", "PRCT", "ACRS", "IMVT", "TGTX",
  "HOOK", "RYTM", "ANAB", "ARWR", "INVA", "MDXG", "OMCL", "PDCO",
  "PNTM", "RCUS", "RLAY", "RXMD", "TBPH", "VRCA", "XNCR", "ZNTL",
  // Financials — regional banks & insurance
  "ACNB", "AMNB", "AROW", "BANF", "BHLB", "BRKL", "BXS", "CBAN",
  "CHCO", "CLBK", "CTBI", "CVBF", "DCOM", "EFSC", "FBNC", "FISI",
  "GABC", "GBCI", "HBCP", "HFWA", "INDB", "KRNY", "LKFN", "MBWM",
  "MBIN", "MOFG", "NBTB", "NBHC", "NKSH", "OFG", "OPBK", "QCRH",
  "RBCAA", "RNST", "SBCF", "TBBK", "TRST", "UVSP", "VBTX", "WABC",
  "WASH", "WSBC", "FFIC", "FRME", "HTBK", "IBCP", "PFBC", "TCBK",
  "HONE", "HBT", "CZWI", "ESSA", "FCCO", "FFBH", "FMBL", "FUNC",
  // Consumer Discretionary
  "BOOT", "CAVA", "CELH", "DKNG", "EXPI", "FIGS", "JACK", "MODG",
  "OPEN", "PENN", "RDFN", "VITL", "IPAR", "PLBY", "PTON", "TIGR",
  "ZUMZ", "PRPL", "LOVE", "VSTO", "XPOF", "ACMR", "CAKE", "EAT",
  "FRGI", "HTHT", "JACK", "KRUS", "NATH", "PBPB", "PLAY", "RRGB",
  // Energy
  "ESTE", "NOG", "NWE", "POWL", "PR", "REX", "SM", "WTI",
  "HLX", "MGY", "MNRL", "PHX", "NGL", "GPOR", "SWN", "CDEV",
  "TALO", "VAALCO", "BATL", "FLNG", "GATO", "LBRT", "MTDR",
  // Industrials & Materials
  "AWI", "BCO", "BMI", "BRC", "DXPE", "GBX", "GEF", "GMS",
  "GVA", "HAYN", "HCC", "HZO", "IBP", "IIIN", "JELD", "KAMN",
  "LGIH", "LMAT", "LNN", "MLI", "MNRO", "MTRN", "MYE", "HTLD",
  "HCSG", "HWKN", "KBAL", "LAUR", "LGF", "LQDT", "MATX", "MGPI",
  "MEC", "MLAB", "CAL", "ASTE", "AEIS", "APOG", "ATI", "BCPC",
  "CATO", "CLW", "CWST", "HCKT", "HMN", "HTLD", "JOUT", "KAI",
];

export const RUSSELL2000_NAMES: Record<string, string> = {
  APPN: "Appian", BAND: "Bandwidth", BIGC: "BigCommerce", BLKB: "Blackbaud",
  COUR: "Coursera", DOMO: "Domo", EVTC: "EVERTEC", EXTR: "Extreme Networks",
  GDYN: "Grid Dynamics", HLIT: "Harmonic", JAMF: "Jamf Holding", LSCC: "Lattice Semiconductor",
  MARA: "Marathon Digital", MGNI: "Magnite", NTGR: "Netgear", PLTK: "Playtika",
  RELY: "Remitly Global", RXRX: "Recursion Pharma", SEAT: "Vivid Seats", STEP: "StepStone Group",
  TRIP: "TripAdvisor", UPST: "Upstart Holdings", YEXT: "Yext", ZETA: "Zeta Global",
  AMSWA: "American Software", CWAN: "Clearwater Analytics", KFRC: "Kforce", NRDS: "NerdWallet",
  RIOT: "Riot Platforms", WULF: "TeraWulf", CIFR: "Cipher Mining", IREN: "IREN Ltd",
  CLOV: "Clover Health", HOOD: "Robinhood", LAZR: "Luminar Technologies", LCID: "Lucid Group",
  JOBY: "Joby Aviation", ACHR: "Archer Aviation", LILM: "Lilium", ARVL: "Arrival",
  ACAD: "ACADIA Pharma", ARDX: "Ardelyx", ATEC: "Alphatec Holdings", AXSM: "Axsome Therapeutics",
  BCRX: "BioCryst Pharma", BCYC: "Bicycle Therapeutics", CNMD: "CONMED",
  HRMY: "Harmony Biosciences", HIMS: "Hims & Hers", IRMD: "IRadimed",
  KMDA: "Kamada", PTCT: "PTC Therapeutics", PRCT: "PROCEPT BioRobotics",
  ACRS: "Aclaris Therapeutics", IMVT: "Immunovant", TGTX: "TG Therapeutics",
  HOOK: "Hookipa Pharma", RYTM: "Rhythm Pharmaceuticals", ANAB: "AnaptysBio",
  ARWR: "Arrowhead Pharma", INVA: "Innoviva", MDXG: "MiMedx", OMCL: "Omnicell",
  PDCO: "Patterson Companies", RCUS: "Arcus Biosciences", TBPH: "Theravance Biopharma",
  ACNB: "ACNB Corp", AMNB: "American National Bankshares", AROW: "Arrow Financial",
  BANF: "BancFirst", BHLB: "Berkshire Hills Bancorp", BRKL: "Brookline Bancorp",
  BXS: "BancorpSouth", CBAN: "Colony Bankcorp", CHCO: "City Holding",
  CLBK: "Columbia Financial", CTBI: "Community Bankshares", CVBF: "CVB Financial",
  DCOM: "Dime Community Bancshares", EFSC: "Enterprise Financial Services",
  FBNC: "First Bancorp", FISI: "Financial Institutions", GABC: "German American Bancorp",
  GBCI: "Glacier Bancorp", HBCP: "Home Bancorp", HFWA: "Heritage Financial",
  INDB: "Independent Bank Group", KRNY: "Kearny Financial", LKFN: "Lakeland Financial",
  MBWM: "Macatawa Bank", MBIN: "Merchants Financial", MOFG: "MidWestOne Financial",
  NBTB: "NBT Bancorp", NBHC: "National Western Financial", NKSH: "National Bankshares",
  OFG: "OFG Bancorp", OPBK: "OP Bancorp", QCRH: "QCR Holdings", RBCAA: "Republic Bancorp",
  RNST: "Renasant", SBCF: "Seacoast Banking", TBBK: "The Bancorp", TRST: "TrustCo Bancorp",
  UVSP: "Univest Financial", VBTX: "Veritex Holdings", WABC: "Westamerica Bancorp",
  WASH: "Washington Trust", WSBC: "WesBanco", FFIC: "Flushing Financial",
  FRME: "First Merchants", HTBK: "Heritage Commerce", IBCP: "Independent Bank",
  PFBC: "Preferred Bank", TCBK: "Trico Bancshares", HONE: "HarborOne Bancorp",
  HBT: "Heartland BancCorp", ESSA: "ESSA Bancorp", FCCO: "First Community",
  BOOT: "Boot Barn", CAVA: "CAVA Group", CELH: "Celsius Holdings",
  DKNG: "DraftKings", EXPI: "eXp World Holdings", FIGS: "FIGS",
  JACK: "Jack in the Box", MODG: "Topgolf Callaway Brands",
  OPEN: "Opendoor Technologies", PENN: "PENN Entertainment", RDFN: "Redfin",
  VITL: "Vital Farms", IPAR: "Inter Parfums", PLBY: "PLBY Group", PTON: "Peloton",
  TIGR: "UP Fintech", ZUMZ: "Zumiez", PRPL: "Purple Innovation", LOVE: "Lovesac",
  VSTO: "Vista Outdoor", XPOF: "Xponential Fitness", CAKE: "Cheesecake Factory",
  EAT: "Brinker International", FRGI: "Fiesta Restaurant", KRUS: "Kura Sushi",
  NATH: "Nathan's Famous", PBPB: "Potbelly", PLAY: "Dave & Buster's", RRGB: "Red Robin",
  ESTE: "Earthstone Energy", NOG: "Northern Oil & Gas", NWE: "NorthWestern Energy",
  POWL: "Powell Industries", PR: "Permian Resources", REX: "REX Energy",
  SM: "SM Energy", WTI: "W&T Offshore", HLX: "Helix Energy", MGY: "Magnolia Oil & Gas",
  MNRL: "Brigham Minerals", PHX: "PHX Minerals", NGL: "NGL Energy Partners",
  GPOR: "Gulfport Energy", SWN: "Southwestern Energy", CDEV: "Centennial Resource",
  TALO: "Talos Energy", VAALCO: "VAALCO Energy", LBRT: "Liberty Energy", MTDR: "Matador Resources",
  AWI: "Armstrong World Industries", BCO: "Brink's", BMI: "Badger Meter",
  BRC: "Brady Corp", DXPE: "DXP Enterprises", GBX: "Greenbrier Companies",
  GEF: "Greif", GMS: "GMS Inc", GVA: "Granite Construction",
  HAYN: "Haynes International", HCC: "Warrior Met Coal", HZO: "MarineMax",
  IBP: "Installed Building Products", IIIN: "Insteel Industries", JELD: "JELD-WEN",
  KAMN: "Kaman", LGIH: "LGI Homes", LMAT: "LeMaitre Vascular",
  LNN: "Lindsay Corp", MLI: "Mueller Industries", MNRO: "Monro",
  MTRN: "Materion", MYE: "Myers Industries", HWKN: "Hawkins",
  LAUR: "Laureate Education", LGF: "Lions Gate Entertainment", LQDT: "Liquidity Services",
  MATX: "Matson", MGPI: "MGP Ingredients", MEC: "Mayville Engineering",
  MLAB: "Mesa Labs", CAL: "Caleres", ASTE: "Astec Industries",
  AEIS: "Advanced Energy Industries", APOG: "Apogee Enterprises",
  BCPC: "Balchem", CATO: "Cato", CLW: "Clearwater Paper",
  CWST: "Casella Waste Systems", HCKT: "Hackett Group", HMN: "Horace Mann",
  JOUT: "Johnson Outdoors", KAI: "Kadant",
};
