export const RUSSELL2000_TICKERS = [
  // Technology
  "APPN", "BAND", "BLKB", "COUR", "DOMO", "EVTC", "EXTR",
  "GDYN", "HLIT", "LSCC", "MARA", "MGNI", "NTGR", "PLTK",
  "RELY", "RXRX", "SEAT", "STEP", "TRIP", "UPST", "YEXT", "ZETA",
  "CWAN", "KFRC", "NRDS", "RIOT", "WULF", "CIFR", "IREN",
  "CLOV", "HOOD", "LCID", "JOBY", "ACHR", // Healthcare & Biotech
  "ACAD", "ARDX", "ATEC", "AXSM", "BCRX", "CNMD", "HRMY",
  "HIMS", "IRMD", "KMDA", "PTCT", "PRCT", "ACRS", "IMVT", "TGTX",
  "RYTM", "ANAB", "ARWR", "INVA", "MDXG", "OMCL", "RCUS", "RLAY", "TBPH", "VRCA", "XNCR", "ZNTL",
  // Financials — regional banks & insurance
  "ACNB", "AROW", "BANF", "CBAN",
  "CHCO", "CLBK", "CTBI", "CVBF", "DCOM", "EFSC", "FBNC", "FISI",
  "GABC", "GBCI", "HBCP", "HFWA", "INDB", "KRNY", "LKFN", "MBWM",
  "MBIN", "NBTB", "NBHC", "NKSH", "OFG", "OPBK", "QCRH",
  "RBCAA", "RNST", "SBCF", "TBBK", "TRST", "UVSP", "WABC",
  "WASH", "WSBC", "FFIC", "FRME", "IBCP", "PFBC", "TCBK",
  "HBT", "CZWI", "FCCO", "FUNC",
  // Consumer Discretionary
  "BOOT", "CAVA", "CELH", "DKNG", "FIGS", "JACK", "OPEN", "PENN", "VITL", "IPAR", "PLBY", "PTON", "TIGR",
  "ZUMZ", "PRPL", "LOVE", "XPOF", "ACMR", "CAKE", "EAT",
  "JACK", "KRUS", "NATH", "PLAY", "RRGB",
  // Energy
  "NOG", "NWE", "POWL", "PR", "REX", "SM", "WTI",
  "HLX", "MGY", "NGL", "GPOR", "TALO", "BATL", "FLNG", "LBRT", "MTDR",
  // Industrials & Materials
  "AWI", "BCO", "BMI", "BRC", "DXPE", "GBX", "GEF", "GVA", "HCC", "HZO", "IBP", "IIIN", "JELD", "LGIH", "LMAT", "LNN", "MLI", "MNRO", "MTRN", "MYE", "HTLD",
  "HCSG", "HWKN", "LAUR", "LQDT", "MATX", "MGPI",
  "MEC", "MLAB", "CAL", "ASTE", "AEIS", "APOG", "ATI", "BCPC",
  "CATO", "CLW", "CWST", "HCKT", "HMN", "HTLD", "JOUT", "KAI",
];

export const RUSSELL2000_NAMES: Record<string, string> = {
  APPN: "Appian", BAND: "Bandwidth", BLKB: "Blackbaud",
  COUR: "Coursera", DOMO: "Domo", EVTC: "EVERTEC", EXTR: "Extreme Networks",
  GDYN: "Grid Dynamics", HLIT: "Harmonic", LSCC: "Lattice Semiconductor",
  MARA: "Marathon Digital", MGNI: "Magnite", NTGR: "Netgear", PLTK: "Playtika",
  RELY: "Remitly Global", RXRX: "Recursion Pharma", SEAT: "Vivid Seats", STEP: "StepStone Group",
  TRIP: "TripAdvisor", UPST: "Upstart Holdings", YEXT: "Yext", ZETA: "Zeta Global",
  CWAN: "Clearwater Analytics", KFRC: "Kforce", NRDS: "NerdWallet",
  RIOT: "Riot Platforms", WULF: "TeraWulf", CIFR: "Cipher Mining", IREN: "IREN Ltd",
  CLOV: "Clover Health", HOOD: "Robinhood", LCID: "Lucid Group",
  JOBY: "Joby Aviation", ACHR: "Archer Aviation", ACAD: "ACADIA Pharma", ARDX: "Ardelyx", ATEC: "Alphatec Holdings", AXSM: "Axsome Therapeutics",
  BCRX: "BioCryst Pharma", CNMD: "CONMED",
  HRMY: "Harmony Biosciences", HIMS: "Hims & Hers", IRMD: "IRadimed",
  KMDA: "Kamada", PTCT: "PTC Therapeutics", PRCT: "PROCEPT BioRobotics",
  ACRS: "Aclaris Therapeutics", IMVT: "Immunovant", TGTX: "TG Therapeutics",
  RYTM: "Rhythm Pharmaceuticals", ANAB: "AnaptysBio",
  ARWR: "Arrowhead Pharma", INVA: "Innoviva", MDXG: "MiMedx", OMCL: "Omnicell",
  RCUS: "Arcus Biosciences", TBPH: "Theravance Biopharma",
  ACNB: "ACNB Corp", AROW: "Arrow Financial",
  BANF: "BancFirst", CBAN: "Colony Bankcorp", CHCO: "City Holding",
  CLBK: "Columbia Financial", CTBI: "Community Bankshares", CVBF: "CVB Financial",
  DCOM: "Dime Community Bancshares", EFSC: "Enterprise Financial Services",
  FBNC: "First Bancorp", FISI: "Financial Institutions", GABC: "German American Bancorp",
  GBCI: "Glacier Bancorp", HBCP: "Home Bancorp", HFWA: "Heritage Financial",
  INDB: "Independent Bank Group", KRNY: "Kearny Financial", LKFN: "Lakeland Financial",
  MBWM: "Macatawa Bank", MBIN: "Merchants Financial", NBTB: "NBT Bancorp", NBHC: "National Western Financial", NKSH: "National Bankshares",
  OFG: "OFG Bancorp", OPBK: "OP Bancorp", QCRH: "QCR Holdings", RBCAA: "Republic Bancorp",
  RNST: "Renasant", SBCF: "Seacoast Banking", TBBK: "The Bancorp", TRST: "TrustCo Bancorp",
  UVSP: "Univest Financial", WABC: "Westamerica Bancorp",
  WASH: "Washington Trust", WSBC: "WesBanco", FFIC: "Flushing Financial",
  FRME: "First Merchants", IBCP: "Independent Bank",
  PFBC: "Preferred Bank", TCBK: "Trico Bancshares", HBT: "Heartland BancCorp", FCCO: "First Community",
  BOOT: "Boot Barn", CAVA: "CAVA Group", CELH: "Celsius Holdings",
  DKNG: "DraftKings", FIGS: "FIGS",
  JACK: "Jack in the Box", OPEN: "Opendoor Technologies", PENN: "PENN Entertainment", VITL: "Vital Farms", IPAR: "Inter Parfums", PLBY: "PLBY Group", PTON: "Peloton",
  TIGR: "UP Fintech", ZUMZ: "Zumiez", PRPL: "Purple Innovation", LOVE: "Lovesac",
  XPOF: "Xponential Fitness", CAKE: "Cheesecake Factory",
  EAT: "Brinker International", KRUS: "Kura Sushi",
  NATH: "Nathan's Famous", PLAY: "Dave & Buster's", RRGB: "Red Robin",
  NOG: "Northern Oil & Gas", NWE: "NorthWestern Energy",
  POWL: "Powell Industries", PR: "Permian Resources", REX: "REX Energy",
  SM: "SM Energy", WTI: "W&T Offshore", HLX: "Helix Energy", MGY: "Magnolia Oil & Gas",
  NGL: "NGL Energy Partners",
  GPOR: "Gulfport Energy", TALO: "Talos Energy", LBRT: "Liberty Energy", MTDR: "Matador Resources",
  AWI: "Armstrong World Industries", BCO: "Brink's", BMI: "Badger Meter",
  BRC: "Brady Corp", DXPE: "DXP Enterprises", GBX: "Greenbrier Companies",
  GEF: "Greif", GVA: "Granite Construction",
  HCC: "Warrior Met Coal", HZO: "MarineMax",
  IBP: "Installed Building Products", IIIN: "Insteel Industries", JELD: "JELD-WEN",
  LGIH: "LGI Homes", LMAT: "LeMaitre Vascular",
  LNN: "Lindsay Corp", MLI: "Mueller Industries", MNRO: "Monro",
  MTRN: "Materion", MYE: "Myers Industries", HWKN: "Hawkins",
  LAUR: "Laureate Education", LQDT: "Liquidity Services",
  MATX: "Matson", MGPI: "MGP Ingredients", MEC: "Mayville Engineering",
  MLAB: "Mesa Labs", CAL: "Caleres", ASTE: "Astec Industries",
  AEIS: "Advanced Energy Industries", APOG: "Apogee Enterprises",
  BCPC: "Balchem", CATO: "Cato", CLW: "Clearwater Paper",
  CWST: "Casella Waste Systems", HCKT: "Hackett Group", HMN: "Horace Mann",
  JOUT: "Johnson Outdoors", KAI: "Kadant",
};

export const RUSSELL2000_SECTORS: Record<string, string> = {
  // Software & Tech
  APPN: "Software", BAND: "Software", BLKB: "Software",
  COUR: "Software", DOMO: "Software", EVTC: "Software", EXTR: "Tech Hardware",
  GDYN: "Software", HLIT: "Tech Hardware", LSCC: "Semiconductors",
  MARA: "Software", MGNI: "Software", NTGR: "Tech Hardware", PLTK: "Media",
  RELY: "Financial Services", RXRX: "Pharma & Biotech", SEAT: "Media",
  STEP: "Financial Services", TRIP: "Consumer Services", UPST: "Financial Services",
  YEXT: "Software", ZETA: "Software", CWAN: "Software",
  KFRC: "Prof. Services", NRDS: "Financial Services", RIOT: "Software", WULF: "Software",
  CIFR: "Software", IREN: "Software", CLOV: "Health Services", HOOD: "Financial Services",
  LCID: "Consumer Goods", JOBY: "Transportation",
  ACHR: "Transportation", // Healthcare
  ACAD: "Pharma & Biotech", ARDX: "Pharma & Biotech", ATEC: "Health Services",
  AXSM: "Pharma & Biotech", BCRX: "Pharma & Biotech", CNMD: "Health Services", HRMY: "Pharma & Biotech", HIMS: "Health Services",
  IRMD: "Health Services", KMDA: "Pharma & Biotech", PTCT: "Pharma & Biotech",
  PRCT: "Health Services", ACRS: "Pharma & Biotech", IMVT: "Pharma & Biotech",
  TGTX: "Pharma & Biotech", RYTM: "Pharma & Biotech",
  ANAB: "Pharma & Biotech", ARWR: "Pharma & Biotech", INVA: "Pharma & Biotech",
  MDXG: "Health Services", OMCL: "Health Services", RCUS: "Pharma & Biotech", RLAY: "Pharma & Biotech",
  TBPH: "Pharma & Biotech", VRCA: "Pharma & Biotech",
  XNCR: "Pharma & Biotech", ZNTL: "Pharma & Biotech",
  // Financials — regional banks
  ACNB: "Banks", AROW: "Banks", BANF: "Banks",
  CBAN: "Banks",
  CHCO: "Banks", CLBK: "Banks", CTBI: "Banks", CVBF: "Banks",
  DCOM: "Banks", EFSC: "Banks", FBNC: "Banks", FISI: "Banks",
  GABC: "Banks", GBCI: "Banks", HBCP: "Banks", HFWA: "Banks",
  INDB: "Banks", KRNY: "Banks", LKFN: "Banks", MBWM: "Banks",
  MBIN: "Banks", NBTB: "Banks", NBHC: "Banks",
  NKSH: "Banks", OFG: "Banks", OPBK: "Banks", QCRH: "Banks",
  RBCAA: "Banks", RNST: "Banks", SBCF: "Banks", TBBK: "Banks",
  TRST: "Banks", UVSP: "Banks", WABC: "Banks",
  WASH: "Banks", WSBC: "Banks", FFIC: "Banks", FRME: "Banks",
  IBCP: "Banks", PFBC: "Banks", TCBK: "Banks",
  HBT: "Banks", CZWI: "Banks", FCCO: "Banks", FUNC: "Banks",
  // Consumer
  BOOT: "Retail", CAVA: "Consumer Services", CELH: "Food & Beverage",
  DKNG: "Media", FIGS: "Consumer Goods", JACK: "Consumer Services",
  OPEN: "REITs", PENN: "Consumer Services",
  VITL: "Food & Beverage", IPAR: "Household Products",
  PLBY: "Consumer Goods", PTON: "Consumer Goods", TIGR: "Financial Services",
  ZUMZ: "Retail", PRPL: "Consumer Goods", LOVE: "Consumer Goods",
  XPOF: "Consumer Services", ACMR: "Semiconductors",
  CAKE: "Consumer Services", EAT: "Consumer Services", KRUS: "Consumer Services", NATH: "Food & Beverage",
  PLAY: "Consumer Services", RRGB: "Consumer Services",
  // Energy
  NOG: "Energy", NWE: "Utilities", POWL: "Capital Goods",
  PR: "Energy", REX: "Energy", SM: "Energy", WTI: "Energy", HLX: "Energy",
  MGY: "Energy", NGL: "Energy", GPOR: "Energy",
  TALO: "Energy", BATL: "Energy", FLNG: "Energy", LBRT: "Energy", MTDR: "Energy",
  // Industrials & Materials
  AWI: "Capital Goods", BCO: "Prof. Services", BMI: "Capital Goods", BRC: "Capital Goods",
  DXPE: "Capital Goods", GBX: "Capital Goods", GEF: "Materials", GVA: "Capital Goods", HCC: "Materials", HZO: "Retail",
  IBP: "Capital Goods", IIIN: "Materials", JELD: "Capital Goods", LGIH: "Consumer Goods", LMAT: "Health Services", LNN: "Capital Goods",
  MLI: "Materials", MNRO: "Retail", MTRN: "Materials", MYE: "Capital Goods",
  HTLD: "Transportation", HCSG: "Prof. Services", HWKN: "Materials", LAUR: "Consumer Services", LQDT: "Prof. Services",
  MATX: "Transportation", MGPI: "Food & Beverage", MEC: "Capital Goods",
  MLAB: "Health Services", CAL: "Retail", ASTE: "Capital Goods", AEIS: "Semiconductors",
  APOG: "Capital Goods", ATI: "Materials", BCPC: "Materials", CATO: "Retail",
  CLW: "Materials", CWST: "Prof. Services", HCKT: "Software", HMN: "Insurance",
  JOUT: "Consumer Goods", KAI: "Capital Goods",
};
