export const SP500_TICKERS = [
  "MMM", "AOS", "ABT", "ABBV", "ACN", "ADBE", "AMD", "AES", "AFL", "A",
  "APD", "ABNB", "AKAM", "ALB", "ARE", "ALGN", "ALLE", "LNT", "ALL", "GOOGL",
  "MO", "AMZN", "AMCR", "AEE", "AEP", "AXP", "AIG", "AMT",
  "AWK", "AMP", "AME", "AMGN", "APH", "ADI", "AON", "APA", "AAPL",
  "AMAT", "APTV", "ACGL", "ADM", "ANET", "AJG", "AIZ", "T", "ATO", "ADSK",
  "ADP", "AZO", "AVB", "AVY", "AXON", "BKR", "BALL", "BAC", "BAX", "BDX",
  "WRB", "BBY", "BIIB", "BLK", "BX", "BA", "BMY", "AVGO", "BR",
  "BRO", "BG", "BLDR", "BXP", "CHRW", "CDNS", "CPT", "CPB", "COF", "CAH",
  "CCL", "CARR", "CAT", "CBOE", "CBRE", "CDW", "COR", "CNC",
  "CF", "CRL", "SCHW", "CHTR", "CVX", "CMG", "CB", "CHD", "CI", "CINF",
  "CTAS", "CSCO", "C", "CFG", "CLX", "CME", "CMS", "KO", "CTSH", "CL",
  "CMCSA", "CAG", "COP", "ED", "STZ", "CEG", "COO", "CPRT", "GLW", "CTVA",
  "CSGP", "COST", "CCI", "CSX", "CMI", "CVS", "DHI", "DHR", "DRI",
  "DVA", "DE", "DAL", "DVN", "DXCM", "FANG", "DLR", "DG",
  "DLTR", "D", "DPZ", "DOV", "DOW", "DTE", "DUK", "DD", "ETN",
  "EBAY", "ECL", "EIX", "EW", "EA", "ELV", "LLY", "EMR", "ETR",
  "EOG", "EPAM", "EQT", "EFX", "EQIX", "EQR", "ESS", "EL", "EG",
  "EXC", "EXPE", "EXPD", "EXR", "XOM", "FFIV", "FDS", "FICO", "FAST", "FRT",
  "FDX", "FIS", "FITB", "FSLR", "FE", "F", "FTNT", "FTV",
  "FOXA", "BEN", "FCX", "GRMN", "IT", "GEHC", "GEN", "GNRC", "GD",
  "GE", "GIS", "GM", "GPC", "GILD", "GPN", "GL", "GS", "GWW", "HAL", "HIG",
  "HAS", "HCA", "HSIC", "HSY", "HPE", "HLT", "HD", "HON",
  "HRL", "HST", "HWM", "HPQ", "HUBB", "HUM", "HBAN", "HII", "IBM", "IEX",
  "IDXX", "ITW", "INCY", "IR", "INTC", "ICE", "IFF", "IP", "INTU", "ISRG", "IVZ", "INVH", "IQV", "IRM", "JBHT", "JBL", "JKHY", "J",
  "JNJ", "JCI", "JPM", "KVUE", "KDP", "KEY", "KEYS", "KMB",
  "KIM", "KMI", "KLAC", "KHC", "KR", "LHX", "LH", "LRCX", "LVS",
  "LDOS", "LEN", "LIN", "LYV", "LMT", "L", "LOW", "LULU", "LYB",
  "MTB", "MPC", "MAR", "MLM", "MAS", "MA",
  "MKC", "MCD", "MCK", "MDT", "MET", "META", "MTD", "MGM", "MCHP", "MU",
  "MSFT", "MAA", "MRNA", "TAP", "MDLZ", "MPWR", "MNST", "MCO",
  "MS", "MOS", "MSI", "MSCI", "NDAQ", "NTAP", "NFLX", "NEM", "NWSA",
  "NEE", "NKE", "NI", "NDSN", "NSC", "NTRS", "NOC", "NCLH", "NRG", "NUE",
  "NVDA", "NVR", "NXPI", "ORLY", "OXY", "ODFL", "OMC", "ON", "OKE", "ORCL",

  "OTIS", "PCAR", "PKG", "PANW", "PH", "PAYX", "PYPL", "PNR", "PEP",
  "PFE", "PCG", "PM", "PSX", "PNW", "PNC", "POOL", "PPG", "PPL", "PFG",
  "PG", "PGR", "PLD", "PRU", "PEG", "PTC", "PSA", "PHM", "PWR",
  "QCOM", "DGX", "RL", "RJF", "RTX", "O", "REG", "REGN", "RF", "RSG",
  "RMD", "ROK", "ROL", "ROP", "ROST", "RCL", "SPGI", "CRM", "SBAC", "SLB",
  "STX", "SRE", "NOW", "SHW", "SPG", "SWKS", "SJM", "SNA", "SNDK", "SO",
  "LUV", "SWK", "SBUX", "STT", "STLD", "STE", "SYK", "SYF", "SNPS", "SYY",
  "TMUS", "TROW", "TTWO", "TPR", "TRGP", "TGT", "TEL", "TDY", "TER",
  "TSLA", "TXN", "TXT", "TMO", "TJX", "TSCO", "TT", "TDG", "TRV", "TRMB",
  "TFC", "TYL", "TSN", "USB", "UBER", "UDR", "ULTA", "UNP", "UAL", "UPS",
  "URI", "UNH", "UHS", "VLO", "VTR", "VRSN", "VRSK", "VZ", "VRTX", "V",
  "VST", "VMC", "WAB", "WMT", "WBD", "WDAY", "WEC", "WFC", "WELL",
  "WST", "WDC", "WTW", "WMB", "WYNN", "XEL", "XYL", "YUM", "ZBRA", "ZBH", "ZTS",
  "APO", "APP", "ARES", "BKNG", "BNY", "BSX", "CIEN", "CNP", "COHR", "CPAY",
  "CRH", "CRWD", "CVNA", "DASH", "DDOG", "DECK", "DELL", "DOC", "EME", "ERIE",
  "ES", "EVRG", "EXE", "FISV", "FIX", "GDDY", "GEV", "IBKR", "KKR", "LII",
  "MRK", "PLTR", "PODD", "TECH",
  "BF.B", "BRK.B", "CASY", "COIN", "DIS", "HOOD", "LITE", "MRSH",
  "PSKY", "Q", "RVTY", "SATS", "SMCI", "SOLV", "SW", "TKO",
  "TPL", "TTD", "VEEV", "VICI", "VLTO", "VRT", "VTRS", "WAT", "WM", "WSM", "WY", "XYZ",
];

export const TICKER_NAMES: Record<string, string> = {
  MMM: "3M", AOS: "A.O. Smith", ABT: "Abbott Labs", ABBV: "AbbVie", ACN: "Accenture",
  ADBE: "Adobe", AMD: "Advanced Micro Devices", AES: "AES Corp", AFL: "Aflac", A: "Agilent Technologies",
  APD: "Air Products", ABNB: "Airbnb", AKAM: "Akamai", ALB: "Albemarle", ARE: "Alexandria RE",
  ALGN: "Align Technology", ALLE: "Allegion", LNT: "Alliant Energy", ALL: "Allstate", GOOGL: "Alphabet A",
  MO: "Altria", AMZN: "Amazon", AMCR: "Amcor", AEE: "Ameren",
  AAL: "American Airlines", AEP: "American Electric Power", AXP: "American Express", AIG: "American Intl Group", AMT: "American Tower",
  AWK: "American Water Works", AMP: "Ameriprise", AME: "AMETEK", AMGN: "Amgen", APH: "Amphenol",
  ADI: "Analog Devices", AON: "Aon", APA: "APA Corp", AAPL: "Apple",
  AMAT: "Applied Materials", APTV: "Aptiv", ACGL: "Arch Capital", ADM: "Archer-Daniels-Midland", ANET: "Arista Networks",
  AJG: "Arthur J. Gallagher", AIZ: "Assurant", T: "AT&T", ATO: "Atmos Energy", ADSK: "Autodesk",
  ADP: "Automatic Data Processing", AZO: "AutoZone", AVB: "AvalonBay", AVY: "Avery Dennison", AXON: "Axon Enterprise",
  BKR: "Baker Hughes", BALL: "Ball Corp", BAC: "Bank of America", BAX: "Baxter", BDX: "Becton Dickinson",
  WRB: "W.R. Berkley", BBY: "Best Buy", BIO: "Bio-Rad", BIIB: "Biogen", BLK: "BlackRock",
  BX: "Blackstone", BA: "Boeing", BMY: "Bristol-Myers Squibb", AVGO: "Broadcom", BR: "Broadridge",
  BRO: "Brown & Brown", BG: "Bunge", BLDR: "Builders FirstSource", BXP: "BXP", CHRW: "C.H. Robinson",
  CDNS: "Cadence Design", CPT: "Camden Property", CPB: "Campbell Soup", COF: "Capital One", CAH: "Cardinal Health",
  KMX: "CarMax", CCL: "Carnival", CARR: "Carrier Global", CAT: "Caterpillar", CBOE: "Cboe Global Markets",
  CBRE: "CBRE Group", CDW: "CDW Corp", CE: "Celanese", COR: "Cencora", CNC: "Centene",
  CF: "CF Industries", CRL: "Charles River Labs", SCHW: "Charles Schwab", CHTR: "Charter Communications", CVX: "Chevron",
  CMG: "Chipotle", CB: "Chubb", CHD: "Church & Dwight", CI: "Cigna", CINF: "Cincinnati Financial",
  CTAS: "Cintas", CSCO: "Cisco", C: "Citigroup", CFG: "Citizens Financial", CLX: "Clorox",
  CME: "CME Group", CMS: "CMS Energy", KO: "Coca-Cola", CTSH: "Cognizant", CL: "Colgate-Palmolive",
  CMCSA: "Comcast", CAG: "Conagra", COP: "ConocoPhillips", ED: "Consolidated Edison", STZ: "Constellation Brands",
  CEG: "Constellation Energy", COO: "Cooper Companies", CPRT: "Copart", GLW: "Corning", CTVA: "Corteva",
  CSGP: "CoStar Group", COST: "Costco", CCI: "Crown Castle", CSX: "CSX Corp",
  CMI: "Cummins", CVS: "CVS Health", DHI: "D.R. Horton", DHR: "Danaher", DRI: "Darden Restaurants",
  DVA: "DaVita", DE: "Deere & Co", DAL: "Delta Air Lines", XRAY: "Dentsply Sirona", DVN: "Devon Energy",
  DXCM: "DexCom", FANG: "Diamondback Energy", DLR: "Digital Realty", DG: "Dollar General",
  DLTR: "Dollar Tree", D: "Dominion Energy", DPZ: "Domino's Pizza", DOV: "Dover", DOW: "Dow",
  DTE: "DTE Energy", DUK: "Duke Energy", DD: "DuPont", EMN: "Eastman Chemical", ETN: "Eaton",
  EBAY: "eBay", ECL: "Ecolab", EIX: "Edison International", EW: "Edwards Lifesciences", EA: "Electronic Arts",
  ELV: "Elevance Health", LLY: "Eli Lilly", EMR: "Emerson Electric", ENPH: "Enphase Energy", ETR: "Entergy",
  EOG: "EOG Resources", EPAM: "EPAM Systems", EQT: "EQT Corp", EFX: "Equifax", EQIX: "Equinix",
  EQR: "Equity Residential", ESS: "Essex Property", EL: "Estée Lauder", ETSY: "Etsy", EG: "Everest Group",
  EXC: "Exelon", EXPE: "Expedia", EXPD: "Expeditors Intl", EXR: "Extra Space Storage", XOM: "ExxonMobil",
  FFIV: "F5 Networks", FDS: "FactSet", FICO: "Fair Isaac", FAST: "Fastenal", FRT: "Federal Realty",
  FDX: "FedEx", FIS: "Fidelity National Info", FITB: "Fifth Third Bancorp", FSLR: "First Solar", FE: "FirstEnergy",
  FMC: "FMC Corp", F: "Ford Motor", FTNT: "Fortinet", FTV: "Fortive",
  FOXA: "Fox Corp A", BEN: "Franklin Resources", FCX: "Freeport-McMoRan", GRMN: "Garmin",
  IT: "Gartner", GEHC: "GE HealthCare", GEN: "Gen Digital", GNRC: "Generac", GD: "General Dynamics",
  GE: "General Electric", GIS: "General Mills", GM: "General Motors", GPC: "Genuine Parts", GILD: "Gilead Sciences",
  GPN: "Global Payments", GL: "Globe Life", GS: "Goldman Sachs", HAL: "Halliburton", HIG: "Hartford Financial",
  HAS: "Hasbro", HCA: "HCA Healthcare", HSIC: "Henry Schein", HSY: "Hershey", HPE: "HP Enterprise", HLT: "Hilton", HD: "Home Depot", HON: "Honeywell",
  HRL: "Hormel Foods", HST: "Host Hotels", HWM: "Howmet Aerospace", HPQ: "HP Inc", HUBB: "Hubbell",
  HUM: "Humana", HBAN: "Huntington Bancshares", HII: "Huntington Ingalls", IBM: "IBM", IEX: "IDEX Corp",
  IDXX: "IDEXX Laboratories", ITW: "Illinois Tool Works", ILMN: "Illumina", INCY: "Incyte", IR: "Ingersoll Rand",
  INTC: "Intel", ICE: "Intercontinental Exchange", IFF: "Intl Flavors & Fragrances", IP: "International Paper", INTU: "Intuit", ISRG: "Intuitive Surgical", IVZ: "Invesco", INVH: "Invitation Homes", IQV: "IQVIA",
  IRM: "Iron Mountain", JBHT: "J.B. Hunt Transport", JBL: "Jabil", JKHY: "Jack Henry", J: "Jacobs Solutions",
  JNJ: "Johnson & Johnson", JCI: "Johnson Controls", JPM: "JPMorgan Chase", KVUE: "Kenvue", KDP: "Keurig Dr Pepper", KEY: "KeyCorp", KEYS: "Keysight Technologies", KMB: "Kimberly-Clark",
  KIM: "Kimco Realty", KMI: "Kinder Morgan", KLAC: "KLA Corp", KHC: "Kraft Heinz", KR: "Kroger",
  LHX: "L3Harris Technologies", LH: "Laboratory Corp", LRCX: "Lam Research", LW: "Lamb Weston", LVS: "Las Vegas Sands",
  LDOS: "Leidos", LEN: "Lennar", LIN: "Linde", LYV: "Live Nation", LKQ: "LKQ Corp",
  LMT: "Lockheed Martin", L: "Loews", LOW: "Lowe's", LULU: "Lululemon", LYB: "LyondellBasell",
  MTB: "M&T Bank", MPC: "Marathon Petroleum", MKTX: "MarketAxess", MAR: "Marriott",
  MLM: "Martin Marietta", MAS: "Masco", MA: "Mastercard", MTCH: "Match Group",
  MKC: "McCormick", MCD: "McDonald's", MCK: "McKesson", MDT: "Medtronic", MET: "MetLife",
  META: "Meta Platforms", MTD: "Mettler-Toledo", MGM: "MGM Resorts", MCHP: "Microchip Technology", MU: "Micron Technology",
  MSFT: "Microsoft", MAA: "Mid-America Apartment", MRNA: "Moderna", MHK: "Mohawk Industries", MOH: "Molina Healthcare",
  TAP: "Molson Coors", MDLZ: "Mondelez", MPWR: "Monolithic Power", MNST: "Monster Beverage", MCO: "Moody's",
  MS: "Morgan Stanley", MOS: "Mosaic", MSI: "Motorola Solutions", MSCI: "MSCI Inc", NDAQ: "Nasdaq",
  NTAP: "NetApp", NFLX: "Netflix", NEM: "Newmont", NWSA: "News Corp A",
  NEE: "NextEra Energy", NKE: "Nike", NI: "NiSource", NDSN: "Nordson", NSC: "Norfolk Southern",
  NTRS: "Northern Trust", NOC: "Northrop Grumman", NCLH: "Norwegian Cruise Line", NRG: "NRG Energy", NUE: "Nucor",
  NVDA: "NVIDIA", NVR: "NVR Inc", NXPI: "NXP Semiconductors", ORLY: "O'Reilly Automotive", OXY: "Occidental Petroleum",
  ODFL: "Old Dominion Freight", OMC: "Omnicom", ON: "ON Semiconductor", OKE: "ONEOK", ORCL: "Oracle",
  OTIS: "Otis Worldwide", PCAR: "PACCAR", PKG: "Packaging Corp", PANW: "Palo Alto Networks", PH: "Parker Hannifin",
  PAYX: "Paychex", PAYC: "Paycom", PYPL: "PayPal", PNR: "Pentair", PEP: "PepsiCo",
  PFE: "Pfizer", PCG: "PG&E", PM: "Philip Morris", PSX: "Phillips 66", PNW: "Pinnacle West",
  PNC: "PNC Financial", POOL: "Pool Corp", PPG: "PPG Industries", PPL: "PPL Corp", PFG: "Principal Financial",
  PG: "Procter & Gamble", PGR: "Progressive", PLD: "Prologis", PRU: "Prudential Financial", PEG: "PSEG",
  PTC: "PTC Inc", PSA: "Public Storage", PHM: "PulteGroup", QRVO: "Qorvo", PWR: "Quanta Services",
  QCOM: "Qualcomm", DGX: "Quest Diagnostics", RL: "Ralph Lauren", RJF: "Raymond James", RTX: "RTX Corp",
  O: "Realty Income", REG: "Regency Centers", REGN: "Regeneron", RF: "Regions Financial", RSG: "Republic Services",
  RMD: "ResMed", ROK: "Rockwell Automation", ROL: "Rollins", ROP: "Roper Technologies", ROST: "Ross Stores",
  RCL: "Royal Caribbean", SPGI: "S&P Global", CRM: "Salesforce", SBAC: "SBA Communications", SLB: "SLB",
  STX: "Seagate Technology", SRE: "Sempra", NOW: "ServiceNow", SHW: "Sherwin-Williams",
  SPG: "Simon Property", SWKS: "Skyworks Solutions", SJM: "J.M. Smucker", SNA: "Snap-on", SNDK: "SanDisk", SO: "Southern Co",
  LUV: "Southwest Airlines", SWK: "Stanley Black & Decker", SBUX: "Starbucks", STT: "State Street", STLD: "Steel Dynamics",
  STE: "STERIS", SYK: "Stryker", SYF: "Synchrony Financial", SNPS: "Synopsys", SYY: "Sysco",
  TMUS: "T-Mobile US", TROW: "T. Rowe Price", TTWO: "Take-Two Interactive", TPR: "Tapestry", TRGP: "Targa Resources",
  TGT: "Target", TEL: "TE Connectivity", TDY: "Teledyne Technologies", TFX: "Teleflex", TER: "Teradyne",
  TSLA: "Tesla", TXN: "Texas Instruments", TXT: "Textron", TMO: "Thermo Fisher Scientific", TJX: "TJX Companies",
  TSCO: "Tractor Supply", TT: "Trane Technologies", TDG: "TransDigm", TRV: "Travelers", TRMB: "Trimble",
  TFC: "Truist Financial", TYL: "Tyler Technologies", TSN: "Tyson Foods", USB: "U.S. Bancorp", UBER: "Uber",
  UDR: "UDR Inc", ULTA: "Ulta Beauty", UNP: "Union Pacific", UAL: "United Airlines", UPS: "UPS",
  URI: "United Rentals", UNH: "UnitedHealth Group", UHS: "Universal Health Services", VLO: "Valero Energy", VTR: "Ventas",
  VRSN: "VeriSign", VRSK: "Verisk Analytics", VZ: "Verizon", VRTX: "Vertex Pharmaceuticals", V: "Visa",
  VST: "Vistra Corp", VMC: "Vulcan Materials", WAB: "Wabtec", WMT: "Walmart",
  WBD: "Warner Bros. Discovery", WDAY: "Workday", WEC: "WEC Energy", WFC: "Wells Fargo", WELL: "Welltower",
  WST: "West Pharmaceutical", WDC: "Western Digital", WTW: "Willis Towers Watson", WMB: "Williams Companies", WYNN: "Wynn Resorts",
  XEL: "Xcel Energy", XYL: "Xylem", YUM: "Yum! Brands", ZBRA: "Zebra Technologies", ZBH: "Zimmer Biomet", ZTS: "Zoetis",
  APO: "Apollo Global Management", APP: "AppLovin", ARES: "Ares Management",
  BKNG: "Booking Holdings", BNY: "BNY Mellon", BSX: "Boston Scientific",
  CIEN: "Ciena", CNP: "CenterPoint Energy", COHR: "Coherent", CPAY: "Corpay",
  CRH: "CRH", CRWD: "CrowdStrike", CVNA: "Carvana", DASH: "DoorDash",
  DDOG: "Datadog", DECK: "Deckers Outdoor", DELL: "Dell Technologies", DOC: "Healthpeak Properties",
  EME: "EMCOR Group", ERIE: "Erie Indemnity", ES: "Eversource Energy", EVRG: "Evergy",
  EXE: "Expand Energy", FISV: "Fiserv", FIX: "Comfort Systems", GDDY: "GoDaddy",
  GEV: "GE Vernova", IBKR: "Interactive Brokers", KKR: "KKR & Co", LII: "Lennox International",
  MRK: "Merck", PLTR: "Palantir Technologies", PODD: "Insulet", TECH: "Bio-Techne",
  "BF.B": "Brown-Forman B", "BRK.B": "Berkshire Hathaway B", CASY: "Casey's General Stores",
  COIN: "Coinbase", DIS: "Walt Disney", FOX: "Fox Corp B", GWW: "W.W. Grainger",
  HOOD: "Robinhood Markets", LITE: "Lumentum Holdings", MRSH: "Marsh McLennan",
  NWS: "News Corp B", PSKY: "Puresky Energy", Q: "Quintiles IMS",
  RVTY: "Revvity", SATS: "EchoStar", SMCI: "Super Micro Computer",
  SOLV: "Solventum", SW: "Smurfit WestRock", TKO: "TKO Group",
  TPL: "Texas Pacific Land", TTD: "The Trade Desk", VEEV: "Veeva Systems",
  VICI: "VICI Properties", VLTO: "Veralto", VRT: "Vertiv Holdings",
  VTRS: "Viatris", WAT: "Waters Corp", WM: "Waste Management",
  WSM: "Williams-Sonoma", WY: "Weyerhaeuser", XYZ: "Block Inc",
};

export const SP500_SECTORS: Record<string, string> = {
  MMM: "Capital Goods", AOS: "Capital Goods", ABT: "Health Services", ABBV: "Pharma & Biotech",
  ACN: "Software", ADBE: "Software", AMD: "Semiconductors", AES: "Utilities",
  AFL: "Insurance", A: "Health Services", APD: "Materials", ABNB: "Consumer Services",
  AKAM: "Software", ALB: "Materials", ARE: "REITs", ALGN: "Health Services",
  ALLE: "Capital Goods", LNT: "Utilities", ALL: "Insurance", GOOGL: "Media",
  MO: "Food & Beverage", AMZN: "Retail", AMCR: "Materials",
  AEE: "Utilities", AAL: "Transportation", AEP: "Utilities", AXP: "Financial Services",
  AIG: "Insurance", AMT: "REITs", AWK: "Utilities", AMP: "Financial Services",
  AME: "Capital Goods", AMGN: "Pharma & Biotech", APH: "Tech Hardware", ADI: "Semiconductors",
  AON: "Insurance", APA: "Energy", AAPL: "Tech Hardware",
  AMAT: "Semiconductors", APTV: "Consumer Goods", ACGL: "Insurance", ADM: "Food & Beverage",
  ANET: "Tech Hardware", AJG: "Insurance", AIZ: "Insurance", T: "Telecom",
  ATO: "Utilities", ADSK: "Software", ADP: "Software", AZO: "Retail",
  AVB: "REITs", AVY: "Materials", AXON: "Capital Goods", BKR: "Energy",
  BALL: "Materials", BAC: "Banks", BAX: "Health Services", BDX: "Health Services",
  WRB: "Insurance", BBY: "Retail", BIO: "Health Services", BIIB: "Pharma & Biotech",
  BLK: "Financial Services", BX: "Financial Services", BA: "Capital Goods", BMY: "Pharma & Biotech",
  AVGO: "Semiconductors", BR: "Software", BRO: "Insurance", BG: "Food & Beverage",
  BLDR: "Capital Goods", BXP: "REITs", CHRW: "Transportation", CDNS: "Software",
  CPT: "REITs", CPB: "Food & Beverage", COF: "Financial Services", CAH: "Health Services",
  KMX: "Retail", CCL: "Consumer Services", CARR: "Capital Goods", CAT: "Capital Goods",
  CBOE: "Financial Services", CBRE: "REITs", CDW: "Tech Hardware", CE: "Materials",
  COR: "Health Services", CNC: "Health Services", CF: "Materials", CRL: "Health Services",
  SCHW: "Financial Services", CHTR: "Telecom", CVX: "Energy", CMG: "Consumer Services",
  CB: "Insurance", CHD: "Household Products", CI: "Health Services", CINF: "Insurance",
  CTAS: "Prof. Services", CSCO: "Tech Hardware", C: "Banks", CFG: "Banks",
  CLX: "Household Products", CME: "Financial Services", CMS: "Utilities",
  KO: "Food & Beverage", CTSH: "Software", CL: "Household Products",
  CMCSA: "Telecom", CAG: "Food & Beverage", COP: "Energy", ED: "Utilities",
  STZ: "Food & Beverage", CEG: "Utilities", COO: "Health Services", CPRT: "Transportation",
  GLW: "Tech Hardware", CTVA: "Materials", CSGP: "REITs", COST: "Food & Beverage",
  CCI: "REITs", CSX: "Transportation", CMI: "Capital Goods",
  CVS: "Health Services", DHI: "Consumer Goods", DHR: "Health Services", DRI: "Consumer Services",
  DVA: "Health Services", DE: "Capital Goods", DAL: "Transportation", XRAY: "Health Services",
  DVN: "Energy", DXCM: "Health Services", FANG: "Energy", DLR: "REITs",
  DG: "Retail", DLTR: "Retail", D: "Utilities",
  DPZ: "Consumer Services", DOV: "Capital Goods", DOW: "Materials", DTE: "Utilities",
  DUK: "Utilities", DD: "Materials", EMN: "Materials", ETN: "Capital Goods",
  EBAY: "Retail", ECL: "Materials", EIX: "Utilities", EW: "Health Services",
  EA: "Media", ELV: "Health Services", LLY: "Pharma & Biotech", EMR: "Capital Goods",
  ENPH: "Semiconductors", ETR: "Utilities", EOG: "Energy", EPAM: "Software",
  EQT: "Energy", EFX: "Prof. Services", EQIX: "REITs", EQR: "REITs", ESS: "REITs",
  EL: "Household Products", ETSY: "Retail", EG: "Insurance", EXC: "Utilities",
  EXPE: "Consumer Services", EXPD: "Transportation", EXR: "REITs", XOM: "Energy",
  FFIV: "Tech Hardware", FDS: "Financial Services", FICO: "Software", FAST: "Capital Goods",
  FRT: "REITs", FDX: "Transportation", FIS: "Software", FITB: "Banks",
  FSLR: "Semiconductors", FE: "Utilities", FMC: "Materials",
  F: "Consumer Goods", FTNT: "Software", FTV: "Capital Goods",
  FOXA: "Media", BEN: "Financial Services", FCX: "Materials",
  GRMN: "Tech Hardware", IT: "Software", GEHC: "Health Services", GEN: "Software",
  GNRC: "Capital Goods", GD: "Capital Goods", GE: "Capital Goods",
  GIS: "Food & Beverage", GM: "Consumer Goods", GPC: "Retail",
  GILD: "Pharma & Biotech", GPN: "Software", GL: "Insurance", GS: "Financial Services",
  HAL: "Energy", HIG: "Insurance", HAS: "Consumer Goods", HCA: "Health Services",
  HSIC: "Health Services", HSY: "Food & Beverage", HPE: "Tech Hardware",
  HLT: "Consumer Services", HD: "Retail", HON: "Capital Goods",
  HRL: "Food & Beverage", HST: "REITs", HWM: "Capital Goods", HPQ: "Tech Hardware",
  HUBB: "Capital Goods", HUM: "Health Services", HBAN: "Banks", HII: "Capital Goods",
  IBM: "Software", IEX: "Capital Goods", IDXX: "Health Services", ITW: "Capital Goods",
  ILMN: "Pharma & Biotech", INCY: "Pharma & Biotech", IR: "Capital Goods",
  INTC: "Semiconductors", ICE: "Financial Services", IFF: "Materials", IP: "Materials",
  INTU: "Software", ISRG: "Health Services", IVZ: "Financial Services",
  INVH: "REITs", IQV: "Health Services", IRM: "REITs", JBHT: "Transportation",
  JBL: "Tech Hardware", JKHY: "Software", J: "Capital Goods", JNJ: "Pharma & Biotech",
  JCI: "Capital Goods", JPM: "Banks", KVUE: "Household Products", KDP: "Food & Beverage", KEY: "Banks", KEYS: "Tech Hardware",
  KMB: "Household Products", KIM: "REITs", KMI: "Energy", KLAC: "Semiconductors",
  KHC: "Food & Beverage", KR: "Food & Beverage", LHX: "Capital Goods", LH: "Health Services",
  LRCX: "Semiconductors", LW: "Food & Beverage", LVS: "Consumer Services",
  LDOS: "Capital Goods", LEN: "Consumer Goods", LIN: "Materials",
  LYV: "Media", LKQ: "Retail", LMT: "Capital Goods", L: "Financial Services",
  LOW: "Retail", LULU: "Consumer Goods", LYB: "Materials",
  MTB: "Banks", MPC: "Energy", MKTX: "Financial Services",
  MAR: "Consumer Services", MLM: "Materials", MAS: "Capital Goods",
  MA: "Financial Services", MTCH: "Media", MKC: "Food & Beverage", MCD: "Consumer Services",
  MCK: "Health Services", MDT: "Health Services", MET: "Insurance", META: "Media",
  MTD: "Health Services", MGM: "Consumer Services", MCHP: "Semiconductors", MU: "Semiconductors",
  MSFT: "Software", MAA: "REITs", MRNA: "Pharma & Biotech", MHK: "Consumer Goods",
  MOH: "Health Services", TAP: "Food & Beverage", MDLZ: "Food & Beverage",
  MPWR: "Semiconductors", MNST: "Food & Beverage", MCO: "Financial Services",
  MS: "Financial Services", MOS: "Materials", MSI: "Tech Hardware", MSCI: "Financial Services",
  NDAQ: "Financial Services", NTAP: "Tech Hardware", NFLX: "Media", NEM: "Materials",
  NWSA: "Media", NEE: "Utilities", NKE: "Consumer Goods",
  NI: "Utilities", NDSN: "Capital Goods", NSC: "Transportation", NTRS: "Financial Services",
  NOC: "Capital Goods", NCLH: "Consumer Services", NRG: "Utilities", NUE: "Materials",
  NVDA: "Semiconductors", NVR: "Consumer Goods", NXPI: "Semiconductors",
  ORLY: "Retail", OXY: "Energy", ODFL: "Transportation", OMC: "Media",
  ON: "Semiconductors", OKE: "Energy", ORCL: "Software", OTIS: "Capital Goods",
  PCAR: "Capital Goods", PKG: "Materials", PANW: "Software", PH: "Capital Goods",
  PAYX: "Software", PAYC: "Software", PYPL: "Financial Services", PNR: "Capital Goods",
  PEP: "Food & Beverage", PFE: "Pharma & Biotech", PCG: "Utilities", PM: "Food & Beverage",
  PSX: "Energy", PNW: "Utilities", PNC: "Banks", POOL: "Retail",
  PPG: "Materials", PPL: "Utilities", PFG: "Financial Services",
  PG: "Household Products", PGR: "Insurance", PLD: "REITs", PRU: "Insurance",
  PEG: "Utilities", PTC: "Software", PSA: "REITs", PHM: "Consumer Goods",
  QRVO: "Semiconductors", PWR: "Capital Goods", QCOM: "Semiconductors",
  DGX: "Health Services", RL: "Consumer Goods", RJF: "Financial Services",
  RTX: "Capital Goods", O: "REITs", REG: "REITs", REGN: "Pharma & Biotech",
  RF: "Banks", RSG: "Prof. Services", RMD: "Health Services", ROK: "Capital Goods",
  ROL: "Prof. Services", ROP: "Capital Goods", ROST: "Retail", RCL: "Consumer Services",
  SPGI: "Financial Services", CRM: "Software", SBAC: "REITs", SLB: "Energy",
  STX: "Tech Hardware", SRE: "Utilities", NOW: "Software",
  SHW: "Materials", SPG: "REITs", SWKS: "Semiconductors", SJM: "Food & Beverage",
  SNA: "Capital Goods", SNDK: "Tech Hardware", SO: "Utilities", LUV: "Transportation", SWK: "Capital Goods",
  SBUX: "Consumer Services", STT: "Financial Services", STLD: "Materials",
  STE: "Health Services", SYK: "Health Services", SYF: "Financial Services",
  SNPS: "Software", SYY: "Food & Beverage", TMUS: "Telecom", TROW: "Financial Services",
  TTWO: "Media", TPR: "Consumer Goods", TRGP: "Energy", TGT: "Retail",
  TEL: "Tech Hardware", TDY: "Tech Hardware", TFX: "Health Services", TER: "Semiconductors",
  TSLA: "Consumer Goods", TXN: "Semiconductors", TXT: "Capital Goods", TMO: "Health Services",
  TJX: "Retail", TSCO: "Retail", TT: "Capital Goods", TDG: "Capital Goods",
  TRV: "Insurance", TRMB: "Tech Hardware", TFC: "Banks", TYL: "Software",
  TSN: "Food & Beverage", USB: "Banks", UBER: "Transportation", UDR: "REITs",
  ULTA: "Retail", UNP: "Transportation", UAL: "Transportation", UPS: "Transportation",
  URI: "Capital Goods", UNH: "Health Services", UHS: "Health Services",
  VLO: "Energy", VTR: "REITs", VRSN: "Software", VRSK: "Prof. Services",
  VZ: "Telecom", VRTX: "Pharma & Biotech", V: "Financial Services", VST: "Utilities",
  VMC: "Materials", WAB: "Capital Goods", WMT: "Food & Beverage",
  WBD: "Media", WDAY: "Software", WEC: "Utilities", WFC: "Banks", WELL: "REITs",
  WST: "Health Services", WDC: "Tech Hardware", WTW: "Insurance", WMB: "Energy",
  WYNN: "Consumer Services", XEL: "Utilities", XYL: "Capital Goods",
  YUM: "Consumer Services", ZBRA: "Tech Hardware", ZBH: "Health Services", ZTS: "Pharma & Biotech",
  APO: "Financial Services", APP: "Software", ARES: "Financial Services",
  BKNG: "Consumer Services", BNY: "Banks", BSX: "Health Services",
  CIEN: "Tech Hardware", CNP: "Utilities", COHR: "Tech Hardware", CPAY: "Financial Services",
  CRH: "Materials", CRWD: "Software", CVNA: "Retail", DASH: "Consumer Services",
  DDOG: "Software", DECK: "Consumer Goods", DELL: "Tech Hardware", DOC: "REITs",
  EME: "Capital Goods", ERIE: "Insurance", ES: "Utilities", EVRG: "Utilities",
  EXE: "Energy", FISV: "Financial Services", FIX: "Capital Goods", GDDY: "Software",
  GEV: "Capital Goods", IBKR: "Financial Services", KKR: "Financial Services", LII: "Capital Goods",
  MRK: "Pharma & Biotech", PLTR: "Software", PODD: "Health Services", TECH: "Health Services",
  "BF.B": "Food & Beverage", "BRK.B": "Financial Services", CASY: "Food & Beverage",
  COIN: "Financial Services", DIS: "Media", FOX: "Media", GWW: "Capital Goods",
  HOOD: "Financial Services", LITE: "Tech Hardware", MRSH: "Insurance",
  NWS: "Media", PSKY: "Energy", Q: "Software",
  RVTY: "Health Services", SATS: "Telecom", SMCI: "Tech Hardware",
  SOLV: "Health Services", SW: "Materials", TKO: "Media",
  TPL: "Energy", TTD: "Software", VEEV: "Software",
  VICI: "REITs", VLTO: "Capital Goods", VRT: "Capital Goods",
  VTRS: "Pharma & Biotech", WAT: "Health Services", WM: "Prof. Services",
  WSM: "Retail", WY: "REITs", XYZ: "Financial Services",
};
