/**
 * Fetches all active US-listed common stocks from Polygon and writes
 * lib/all-tickers.ts with ALL_TICKERS (string[]) and ALL_TICKER_NAMES (Record<string, string>).
 *
 * Re-run whenever you want to pick up new listings or ticker renames:
 *   npm run generate:tickers
 */

import { writeFileSync } from "fs";
import { join } from "path";

const API_KEY = process.env.POLYGON_API_KEY!;

interface PolygonTicker {
  ticker: string;
}

async function fetchAllTickers(): Promise<PolygonTicker[]> {
  const results: PolygonTicker[] = [];
  let url = `https://api.polygon.io/v3/reference/tickers?market=stocks&locale=us&type=CS&active=true&limit=1000&apiKey=${API_KEY}`;

  while (url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Polygon error ${res.status}: ${await res.text()}`);
    const data = await res.json();
    for (const t of data.results ?? []) {
      results.push({ ticker: t.ticker });
    }
    process.stdout.write(`\r  Fetched ${results.length} tickers...`);
    // next_url already contains the apiKey
    url = data.next_url ? `${data.next_url}&apiKey=${API_KEY}` : "";
  }

  console.log(`\r  Fetched ${results.length} tickers total.`);
  return results;
}

(async () => {
  console.log(`Fetching all active US common stocks from Polygon...\n`);

  const tickers = await fetchAllTickers();
  tickers.sort((a, b) => a.ticker.localeCompare(b.ticker));

  const tickerList = tickers.map((t) => t.ticker);

  const output = [
    `// Auto-generated by scripts/generate-tickers.ts — do not edit by hand.`,
    `// Re-run \`npm run generate:tickers\` to refresh.`,
    `// Last updated: ${new Date().toISOString().split("T")[0]} · ${tickers.length} tickers`,
    ``,
    `export const ALL_TICKERS: string[] = ${JSON.stringify(tickerList, null, 2)};`,
  ].join("\n");

  const outPath = join(process.cwd(), "lib", "all-tickers.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(`\nWritten to lib/all-tickers.ts (${tickers.length} tickers).`);
})();
